const { PERMISSIONS, ALL_PERMISSIONS } = require('./permissions');

const ROLE_PERMISSIONS = Object.freeze({
  'super-admin': ALL_PERMISSIONS,
  'management-admin': Object.freeze([
    PERMISSIONS.MEMBERS.VIEW,
    PERMISSIONS.MEMBERS.CREATE,
    PERMISSIONS.MEMBERS.EDIT,
    PERMISSIONS.MEMBERS.ARCHIVE,
    ...Object.values(PERMISSIONS.APPLICATIONS),
    ...Object.values(PERMISSIONS.ACTIVITIES),
    ...Object.values(PERMISSIONS.NEWS),
    ...Object.values(PERMISSIONS.GALLERY),
    ...Object.values(PERMISSIONS.CONTACT),
    PERMISSIONS.DOCUMENTS.VIEW,
    PERMISSIONS.DOCUMENTS.UPLOAD,
    PERMISSIONS.DOCUMENTS.EDIT,
    PERMISSIONS.DOCUMENTS.DOWNLOAD,
    PERMISSIONS.DOCUMENTS.CHANGE_ACCESS,
    PERMISSIONS.DOCUMENTS.APPROVE,
    PERMISSIONS.DOCUMENTS.DELETE,
    PERMISSIONS.COMMITTEE.VIEW,
    PERMISSIONS.COMMITTEE.MANAGE,
    PERMISSIONS.SETTINGS.VIEW,
  ]),
  'finance-admin': Object.freeze([
    PERMISSIONS.MEMBERS.VIEW,
    ...Object.values(PERMISSIONS.FINANCE),
    PERMISSIONS.DOCUMENTS.VIEW,
    PERMISSIONS.DOCUMENTS.UPLOAD,
    PERMISSIONS.DOCUMENTS.EDIT,
    PERMISSIONS.DOCUMENTS.DOWNLOAD,
    PERMISSIONS.DOCUMENTS.CHANGE_ACCESS,
    PERMISSIONS.DOCUMENTS.APPROVE,
    PERMISSIONS.DOCUMENTS.DELETE,
  ]),
  'content-admin': Object.freeze([
    PERMISSIONS.ACTIVITIES.VIEW,
    PERMISSIONS.ACTIVITIES.CREATE,
    PERMISSIONS.ACTIVITIES.EDIT,
    PERMISSIONS.ACTIVITIES.PUBLISH,
    PERMISSIONS.NEWS.VIEW,
    PERMISSIONS.NEWS.CREATE,
    PERMISSIONS.NEWS.EDIT,
    PERMISSIONS.NEWS.PUBLISH,
    ...Object.values(PERMISSIONS.GALLERY),
    ...Object.values(PERMISSIONS.CONTACT),
    PERMISSIONS.DOCUMENTS.VIEW,
    PERMISSIONS.DOCUMENTS.DOWNLOAD,
  ]),
});

const SYSTEM_ROLES = Object.freeze(Object.keys(ROLE_PERMISSIONS));

module.exports = { ROLE_PERMISSIONS, SYSTEM_ROLES };
